import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import { Rubik, Roboto_Mono } from 'next/font/google'
import Nav from "@/components/nav/Nav";
const rubik = Rubik({
  variable: "--font-rubik",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={rubik.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
